"""
Django settings for facebox_api project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%24cuv(*k_gh2%3$s-x$mr6c^)%r$#nun-u1gnp_=@$#b@hnu2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('MBOX_DEBUG','True').lower() == 'true'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
ALLOWED_HOSTS = ['localhost','127.0.0.1']
allowed_hosts = os.environ.get('MBOX_ALLOWED_HOSTS')
if allowed_hosts:
    ALLOWED_HOSTS = [token.strip() for token in allowed_hosts.split(',')]

if not DEBUG:
    SECURE_SSL_REDIRECT = True # Redirect HTTP to HTTPS in production
    SESSION_COOKIE_SECURE = True  # Use secure cookies
    CSRF_COOKIE_SECURE = True  # Use secure CSRF cookies
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Using Elastic IP in AWS needs this. Otherwise, a cross-origin error is thrown
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000','http://localhost:8000']
if allowed_hosts:
    CSRF_TRUSTED_ORIGINS.extend(['https://'+token for token in allowed_hosts.split(',')])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_auth_adfs',
    'pgvector.django',
    'facebox_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auth_adfs.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'facebox_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facebox_api.wsgi.application'

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

FILE_UPLOAD_MAX_MEMORY_SIZE = 8 * 1024 * 1024  # 8MB

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('MBOX_DB_NAME'),     # 'facebox',
        'USER': os.environ.get('MBOX_DB_USER'),     # 'postgres',
        'PASSWORD': os.environ.get('MBOX_DB_PASS'), # 'password',
        'HOST': os.environ.get('MBOX_DB_HOST'),     # 'localhost',
        'PORT': os.environ.get('MBOX_DB_PORT')      # '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# In a Docker environment, this environment variables will NOT be defined
# because it is already defined in the YAML file
MEDIA_ROOT = os.environ.get('MBOX_MEDIA_ROOT') 
if not MEDIA_ROOT:
    MEDIA_ROOT = '/mbox/thumbnails/'

UPLOADS_DIRECTORY = os.environ.get('MBOX_UPLOADS_DIRECTORY')
if not UPLOADS_DIRECTORY:
    UPLOADS_DIRECTORY = '/mbox/uploads/'

LOG_DIRECTORY = os.environ.get('MBOX_LOG_DIRECTORY')
if not LOG_DIRECTORY:
    LOG_DIRECTORY = '/mbox/logs/'
LOG_SIZE = os.environ.get('MBOX_LOG_SIZE')
if not LOG_SIZE:
    LOG_SIZE = 33554432
else:
    LOG_SIZE = int(LOG_SIZE)

BLOB_STORAGE = os.environ.get('MBOX_BLOB_STORAGE')
if not BLOB_STORAGE:
    BLOB_STORAGE = '/mbox/blobs/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Microsoft Entra ID (Active Directory) integration
AUTHENTICATION_BACKENDS = [
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Configure django-auth-adfs
AUTH_ADFS = {
    'CLIENT_ID': os.environ.get('AZURE_CLIENT_ID'),
    'RELYING_PARTY_ID': os.environ.get('AZURE_CLIENT_ID'),
    'AUDIENCE': os.environ.get('AZURE_CLIENT_ID'),
    'TENANT_ID': os.environ.get('AZURE_TENANT_ID'),
    'CLIENT_SECRET': os.environ.get('AZURE_CLIENT_SECRET'),
    'CLAIM_MAPPING': {
        'first_name': 'given_name',
        'last_name': 'family_name',
        'email': 'upn',
    },
    'USERNAME_CLAIM': 'upn',
    'GROUPS_CLAIM': 'groups',
    'GROUP_TO_FLAG_MAPPING': { 'is_superuser': ['mbox-editor'], },
    'MIRROR_GROUPS': True,
    'REDIR_URI': os.environ.get('MBOX_REDIR_URI'),         # 'http://localhost:8000/oauth2/callback',
    'LOGIN_EXEMPT_URLS': [
        '^login/$',
        '^admin/$',
        '^admin/login/$',
    ],
}

AZURE_CONNECTION_STRING = os.environ.get('AZURE_CONNECTION_STRING')
AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
MBOX_EDITORS_GROUP = os.environ.get('MBOX_EDITORS_GROUP')
MBOX_SUPERVISORS_GROUP = os.environ.get('MBOX_SUPERVISORS_GROUP')
MBOX_DEVELOPERS_GROUP = os.environ.get('MBOX_DEVELOPERS_GROUP')
MBOX_URL_EXPIRATION = os.environ.get('MBOX_URL_EXPIRATION')
MAX_FILES_PER_STORAGE_BUCKET = os.environ.get('MBOX_MAX_FILES_PER_STORAGE_BUCKET')
REST_USE_JWT = True
DELETE_LOCAL_FILE_AFTER_UPLOAD = True
TARGET_STORAGE = os.environ.get('MBOX_TARGET_STORAGE')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/app/videos/'

LOGGING = {
       'version': 1,
       'disable_existing_loggers': False,
       'formatters': {
            'verbose': {
                'format': '[{asctime}] {levelname} {name} {message}',
                'style': '{',
                'datefmt': '%Y-%m-%d %H:%M:%S',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
       },
       'handlers': {
           'file': {
               'level': 'INFO',
               'class': 'logging.handlers.RotatingFileHandler',
               'filename': LOG_DIRECTORY + 'django.log',
               'maxBytes': LOG_SIZE,
               'backupCount': 10,
               'formatter': 'verbose',
           },
           'mail_admins': {
               'level': 'ERROR',
               'class': 'django.utils.log.AdminEmailHandler',
           }
       },
       'root': {
           'handlers': ['file'],
           'level': os.environ.get('MBOX_ROOT_LOGLEVEL'), 
       },
       'loggers': {
           'django': {
               'handlers': ['file'],
               'level': os.environ.get('MBOX_DJANGO_LOGLEVEL'), 
               'propagate': False,
           },
           'django.request': {
               'handlers': ['mail_admins'],
               'level': os.environ.get('MBOX_REQUEST_LOGLEVEL'),
               'propagate': False,
           },
           'django.db.backends': {
               'handlers': ['file'],
               'level': os.environ.get('MBOX_BACKENDS_LOGLEVEL'),
               'propagate': False,
           },
           'django.security.Authentication': {
               'handlers': ['file'],
               'level': 'INFO',
               'propagate': False,
           },
           'mbox': {
               'handlers': ['file'],
               'level': os.environ.get('MBOX_APP_LOGLEVEL'),
               'propagate': False,
           },
       },
   }
