"""
Django settings for facebox_api project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%24cuv(*k_gh2%3$s-x$mr6c^)%r$#nun-u1gnp_=@$#b@hnu2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('MBOX_DEBUG')

if not DEBUG:
    allowed_hosts = os.environ.get('MBOX_ALLOWED_HOSTS')
    ALLOWED_HOSTS = []
    if allowed_hosts:
        ALLOWED_HOSTS = [token.strip() for token in allowed_hosts.split(',')]
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS in production
    SESSION_COOKIE_SECURE = True  # Use secure cookies
    CSRF_COOKIE_SECURE = True  # Use secure CSRF cookies

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_auth_adfs',
    'pgvector.django',
    'facebox_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auth_adfs.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'facebox_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facebox_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('MBOX_DB_NAME'),     # 'facebox',
        'USER': os.environ.get('MBOX_DB_USER'),     # 'postgres',
        'PASSWORD': os.environ.get('MBOX_DB_PASS'), # 'password',
        'HOST': os.environ.get('MBOX_DB_HOST'),     # 'localhost',
        'PORT': os.environ.get('MBOX_DB_PORT')      # '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# In a Docker environment, this environment variable will NOT be defined
# because it is already defined in the YAML file
MEDIA_ROOT = os.environ.get('MBOX_MEDIA_ROOT') 
if not MEDIA_ROOT:
    MEDIA_ROOT = '/mbox/thumbnails/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Microsoft Entra ID (Active Directory) integration
AUTHENTICATION_BACKENDS = [
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Configure django-auth-adfs
AUTH_ADFS = {
    'CLIENT_ID': os.environ.get('AZURE_CLIENT_ID'),        # 'b210533f-da48-4eeb-97ee-2d5328913a1b',
    'RELYING_PARTY_ID': os.environ.get('AZURE_CLIENT_ID'), # 'b210533f-da48-4eeb-97ee-2d5328913a1b',
    'AUDIENCE': os.environ.get('AZURE_CLIENT_ID'),         # 'b210533f-da48-4eeb-97ee-2d5328913a1b',
    'TENANT_ID': os.environ.get('AZURE_TENANT_ID'),        # '208bb8cb-5f6d-413d-aeec-6be0ce6ad6a5',
    'CLIENT_SECRET': os.environ.get('AZURE_CLIENT_SECRET'),# 'J2p8Q~LkWuOSNf4VADvQp2AtzlPQEWTuXaiWIa1S',
    'CLAIM_MAPPING': {
        'first_name': 'given_name',
        'last_name': 'family_name',
        'email': 'upn',
    },
    'USERNAME_CLAIM': 'upn',
    'GROUPS_CLAIM': 'groups',
    'GROUP_TO_FLAG_MAPPING': { 'is_superuser': ['mbox-editor'], },
    'MIRROR_GROUPS': True,
    'REDIR_URI': os.environ.get('MBOX_REDIR_URI'),         # 'http://localhost:8000/oauth2/callback',
    'LOGIN_EXEMPT_URLS': [
        '^login/$',
        '^admin/$',
        '^admin/login/$',
    ],
}

AZURE_CONNECTION_STRING = os.environ.get('AZURE_CONNECTION_STRING') # 'DefaultEndpointsProtocol=https;AccountName=ayalamedialib;AccountKey=XFv/79FwVeooejIfcHWZ/eI6U3DKtcKZ2ZDb8zwnkcSZgFBJnIz3K0LJvdCKYOGETaZHJ1BZ8zwN+ASt9PPZuQ==;EndpointSuffix=core.windows.net'
MBOX_EDITORS_GROUP = os.environ.get('MBOX_EDITORS_GROUP')  #'20a6b3e3-fe60-4c00-a09d-2061dab62dd9'
MBOX_SUPERVISORS_GROUP = os.environ.get('MBOX_SUPERVISORS_GROUP')
REST_USE_JWT = True

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/app/videos/'

