from django.contrib.auth import views as auth_views
from django.urls import path
from . import views, apis

urlpatterns = [
    # Endpoints that renders an HTML page
    path('', views.app_login, name='app_login'),
    path('login/', views.app_login, name='app_login'),
    path('logout/', views.app_logout, name='app_logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('search/', views.search_face, name='search_face'),
    path('faces/', views.face_search, name='face_search'),
    path('voices/', views.voice_search, name='voice_search'),
    path('videos/', views.video_search, name='video_search'),
    path('photos/', views.photo_search, name='photo_search'),
    path('audios/', views.audio_search, name='audio_search'),
    path('docs/', views.doc_search, name='doc_search'),
    path('media-player/', views.media_player, name='media_player'),
    path('photo-viewer/', views.photo_viewer, name='photo_viewer'),
    path('library/', views.library_viewer, name='library_viewer'),
    path('reports/', views.reports_viewer, name='reports_viewer'),
    path('uploader/', views.uploader, name='uploader'),
    path('api-tester/', views.api_tester, name='api_tester'),
    # APIs that retrieve data
    path('browse-folder/<int:folder_id>/', views.browse_folder, name='browse_folder'),
    path('get-all-groups/', views.get_all_groups, name='get_all_groups'),
    path('get-audit/<int:file_id>/', views.get_audit, name='get_audit'),
    path('get-diary/<int:file_id>/', views.get_diary, name='get_diary'),
    path('get-folder/<int:folder_id>/', views.get_folder, name='get_folder'),
    path('get-folder-id/', views.get_folder_id, name='get_folder_id'),
    path('get-folders/<int:parent_id>/', views.get_folders, name='get_folders'),
    path('get-users/', views.get_users, name='get_users'),
    path('get-groups/', views.get_groups, name='get_groups'),
    path('get-image/<int:face_id>/', views.get_face_image, name='get_face_image'),
    path('get-transcript/<int:file_id>/', views.get_transcript, name='get_transcript'),
    path('get-media/<int:file_id>/', views.get_media, name='get_media'),
    path('get-adjacent-media/<int:file_id>/', views.get_adjacent_media, name='get_adjacent_media'),
    path('get-thumbnail/<int:file_id>/', views.get_thumbnail, name='get_thumbnail'),
    path('get-chunk-thumbnail/<int:chunk_id>/', views.get_chunk_thumbnail, name='get_chunk_thumbnail'),
    path('get-transcript-ratings/', views.get_transcript_ratings, name='get_transcript_ratings'),
    path('get-chunk-ratings/<int:file_id>/', views.get_chunk_ratings, name='get_chunk_ratings'),
    path('get-linked-faces/<int:person_id>/', views.get_linked_faces, name='get_linked_faces'),
    path('search-audit/', views.search_audit, name='search_audit'),
    path('search-face/', views.search_face, name='search_face'),
    path('search-voice/', views.search_voice, name='search_voice'),
    path('search-voice-by-ref/<int:voice_id>/', views.search_voice_by_ref, name='search_voice_by_ref'),
    path('search-media/', views.search_media, name='search_media'),
    path('search-video/', views.search_media, name='search_video'),
    path('search-audio/', views.search_media, name='search_audio'),
    path('search-photo/', views.search_media, name='search_photo'),
    path('search-person/', views.search_person, name='search_person'),
    path('search-transcript/', views.search_transcript, name='search_transcript'),
    path('stream-audio/<int:file_id>/', views.stream_audio, name='stream_audio'),
    # APIs that get information about the data, create data or modify the data
    path('create-folder/<int:parent_id>/', apis.create_folder, name='create_folder'),
    path('delete-file/<int:file_id>/', apis.delete_file, name='delete_file'),
    path('delete-folder/<int:folder_id>/', apis.delete_folder, name='delete_folder'),
    path('get-file-count/<int:folder_id>/', apis.get_file_count, name='get_file_count'),
    path('get-file-position/<int:file_id>/', apis.get_file_position, name='get_file_position'),
    path('get-presigned-url/<int:file_id>/', apis.get_presigned_url, name='get_presigned_url'),
    path('merge-persons/<int:person_id>/', apis.merge_persons, name='merge_persons'),
    path('move-file/<int:file_id>/<int:target_folder>/', apis.move_file, name='move_file'),
    path('move-folder/<int:folder_id>/<int:target_folder>/', apis.move_folder, name='move_folder'),
    path('refresh-folder-stats/<int:folder_id>/', apis.refresh_folder_stats, name='refresh_folder_stats'),
    path('rename-file/<int:file_id>/', apis.rename_file, name='rename_file'),
    path('rename-folder/<int:folder_id>/', apis.rename_folder, name='rename_folder'),
    path('restore-file/<int:file_id>/', apis.restore_file, name='restore_file'),
    path('restore-folder/<int:folder_id>/', apis.restore_folder, name='restore_folder'),
    path('set-file-group/<int:file_id>/<str:group_name>/', apis.set_file_group, name='set_file_group'),
    path('set-file-owner/<int:file_id>/<str:owner_name>/', apis.set_file_owner, name='set_file_owner'),
    path('set-file-permission/<int:file_id>/<int:owner_rights>/<int:group_rights>/<int:domain_rights>/<int:public_rights>/', apis.set_file_permission, name='set_file_permission'),
    path('set-folder-group/<int:folder_id>/<str:group_name>/', apis.set_folder_group, name='set_folder_group'),
    path('set-folder-owner/<int:folder_id>/<str:owner_name>/', apis.set_folder_owner, name='set_folder_owner'),
    path('set-folder-permission/<int:folder_id>/<int:owner_rights>/<int:group_rights>/<int:domain_rights>/<int:public_rights>/', apis.set_folder_permission, name='set_folder_permission'),
    path('set-tree-group/<int:folder_id>/<str:group_name>/', apis.set_tree_group, name='set_tree_group'),
    path('set-tree-owner/<int:folder_id>/<str:owner_name>/', apis.set_tree_owner, name='set_tree_owner'),
    path('set-tree-permission/<int:folder_id>/<int:owner_rights>/<int:group_rights>/<int:domain_rights>/<int:public_rights>/', apis.set_tree_permission, name='set_tree_permission'),
    path('unlink-faces/<int:person_id>/', apis.unlink_faces, name='unlink_faces'),
    path('update-file/<int:file_id>/', apis.update_file, name='update_file'),
    path('update-folder/<int:folder_id>/', apis.update_folder, name='update_folder'),
    path('update-person/<int:person_id>/', apis.update_person, name='update_person'),
    path('update-transcript-segment/<int:file_id>/', apis.update_transcript_segment, name='update_transcript_segment'),
    path('upload-file/<int:folder_id>/', apis.upload_file, name='upload_file')
]

