from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('login/', views.app_login, name='app_login'),
    path('logout/', views.app_logout, name='app_logout'),
    path('search/', views.search_face, name='search_face'),
    path('faces/', views.face_search, name='face_search'),
    path('voices/', views.voice_search, name='voice_search'),
    path('videos/', views.video_search, name='video_search'),
    path('photos/', views.photo_search, name='photo_search'),
    path('audios/', views.audio_search, name='audio_search'),
    path('media-player/', views.media_player, name='media_player'),
    path('photo-viewer/', views.photo_viewer, name='photo_viewer'),
    path('reports/', views.reports_viewer, name='reports_viewer'),
    path('get-audit/<int:file_id>/', views.get_audit, name='get_audit'),
    path('get-diary/<int:file_id>/', views.get_diary, name='get_diary'),
    path('get-folder/<int:folder_id>/', views.get_folder, name='get_folder'),
    path('get-folders/<int:parent_id>/', views.get_folders, name='get_folders'),
    path('get-image/<int:face_id>/', views.get_face_image, name='get_face_image'),
    path('get-transcript/<int:file_id>/', views.get_transcript, name='get_transcript'),
    path('get-media/<int:file_id>/', views.get_media, name='get_media'),
    path('get-adjacent-media/<int:file_id>/', views.get_adjacent_media, name='get_adjacent_media'),
    path('get-thumbnail/<int:file_id>/', views.get_thumbnail, name='get_thumbnail'),
    path('get-file-count/<int:folder_id>/', views.get_file_count, name='get_file_count'),
    path('get-file-position/<int:file_id>/', views.get_file_position, name='get_file_position'),
    path('refresh-folder-stats/<int:folder_id>/', views.refresh_folder_stats, name='refresh_folder_stats'),
    path('search-face/', views.search_face, name='search_face'),
    path('search-voice/', views.search_voice, name='search_voice'),
    path('search-voice-by-ref/<int:voice_id>/', views.search_voice_by_ref, name='search_voice_by_ref'),
    path('search-media/', views.search_media, name='search_media'),
    path('search-video/', views.search_media, name='search_video'),
    path('search-audio/', views.search_media, name='search_audio'),
    path('search-photo/', views.search_media, name='search_photo'),
    path('search-person/', views.search_person, name='search_person'),
    path('stream-audio/<int:file_id>/', views.stream_audio, name='stream_audio'),
    path('update-file/<int:file_id>/', views.update_file, name='update_file'),
    path('update-person/<int:person_id>/', views.update_person, name='update_person'),
    path('update-transcript-segment/<int:file_id>/', views.update_transcript_segment, name='update_transcript_segment'),
]

