# Generated by Django 5.0.7 on 2024-07-30 01:04

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('time_start', models.FloatField(default=0)),
                ('time_end', models.FloatField(default=0)),
                ('box', models.JSONField()),
                ('pose', models.JSONField()),
                ('quality', models.JSONField()),
                ('confidence', models.FloatField(default=-1)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('merged_to', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('face', pgvector.django.vector.VectorField(dimensions=512)),
                ('pose', models.JSONField()),
                ('quality', models.JSONField()),
                ('confidence', models.FloatField()),
                ('face_id', models.BigIntegerField()),
            ],
        ),
    ]
