# Generated by Django 5.0.7 on 2024-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebox_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbxAudit',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=64)),
                ('event_timestamp', models.DateTimeField()),
                ('user_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'fbx_audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FbxFace',
            fields=[
                ('face_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('time_start', models.FloatField()),
                ('time_end', models.FloatField()),
                ('box', models.JSONField()),
                ('pose', models.JSONField()),
                ('quality', models.JSONField()),
                ('confidence', models.FloatField()),
                ('embedding', models.TextField(blank=True, null=True)),
                ('merged_to', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fbx_face',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FbxFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('extension', models.CharField(max_length=16)),
                ('media_type', models.CharField(blank=True, max_length=16, null=True)),
                ('size', models.BigIntegerField()),
                ('file_url', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('date_uploaded', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=64, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=64, null=True)),
                ('owner_rights', models.SmallIntegerField()),
                ('group_rights', models.SmallIntegerField()),
                ('public_rights', models.SmallIntegerField()),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('ip_location', models.CharField(blank=True, max_length=15, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('version', models.SmallIntegerField()),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fbx_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FbxFolder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=2048)),
                ('size', models.BigIntegerField()),
                ('date_created', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
                ('folder_level', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=64, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=64, null=True)),
                ('owner_rights', models.SmallIntegerField()),
                ('group_rights', models.SmallIntegerField()),
                ('public_rights', models.SmallIntegerField()),
                ('file_count', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('subfolder_count', models.IntegerField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('schema_id', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fbx_folder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FbxPerson',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('face', models.TextField(blank=True, null=True)),
                ('pose', models.JSONField(blank=True, null=True)),
                ('quality', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('face_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fbx_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FbxVoice',
            fields=[
                ('voice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_start', models.FloatField()),
                ('time_end', models.FloatField()),
                ('duration', models.FloatField()),
                ('confidence', models.FloatField()),
                ('embedding', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fbx_voice',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
