# Generated by Django 5.0.7 on 2024-08-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebox_app', '0002_fbxaudit_fbxface_fbxfile_fbxfolder_fbxperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbxThumbnail',
            fields=[
                ('thumbnail_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=255)),
                ('used', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'fbx_thumbnail',
                'managed': False,
            },
        ),
    ]
