# Generated by Django 5.1.1 on 2024-09-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebox_app', '0003_fbxthumbnail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fbxaudit',
            table='mbox_audit',
        ),
        migrations.AlterModelTable(
            name='fbxface',
            table='mbox_face',
        ),
        migrations.AlterModelTable(
            name='fbxfile',
            table='mbox_file',
        ),
        migrations.AlterModelTable(
            name='fbxfolder',
            table='mbox_folder',
        ),
        migrations.AlterModelTable(
            name='fbxperson',
            table='mbox_person',
        ),
        migrations.AlterModelTable(
            name='fbxthumbnail',
            table='mbox_thumbnail',
        ),
        migrations.AlterModelTable(
            name='fbxvoice',
            table='mbox_voice',
        ),
    ]
